In [3]:
import names
import random 
import csv
import datetime
import pandas as pd

In [4]:

gender = ["M","F"]
sport_type = ["Football" , "Basketball" , "Tennis", "PingPong" , "Badminton" , "Boxing","Athletic" , "VolleyBall"]
Nation = ["Thai","American","Japanese","Korean" ,"Brazilian","German","Italian","British","French","Russian","Mexican"]
Name = ["Mahidol Sport","ICT Sport","KingKong Sport", "Arm Sport","GD Sport","Underdogs Sport","Man Uay FC","Big Boom FC","Easy Team","Uefa191","CC Sport",
        "Good Team","Pheonix FC","Green Sport","FairPlay Sport","The Best Team","Beyonder","One Above All","Superman","Batman Sport","Rich Kid","GG Sport",
        "XX Sport","Rama Sport","MM Sport","Green Velvet"]
athlete = 1000
team = 25
shuffle = []
for i in range(0,880):
    shuffle.append("Thai")

for i in range(880,890):
    shuffle.append("American")

for i in range(890,900):
    shuffle.append("Japanese")

for i in range(900,940):
    shuffle.append("Korean")

for i in range(940,970):
    shuffle.append("German")

for i in range(970,999):
    shuffle.append("Canadian")

shuffle.append("Italian")

random.shuffle(shuffle)

In [25]:

for x in range(0,athlete):
    print("("
     + "'" + str(x).zfill(5) + "'" +"," + "'" + names.get_first_name()+"'"  +"," + "'" + names.get_last_name()+ "'" + "," + str(random.randint(150,200)) + "," + 
     str(round(random.uniform(40,100),2))+"," + str(random.randint(15,45)) + "," + "'"+ random.choice(gender) +"'" + "," + "'"+random.choice(sport_type)+"'"+ 
     "," + "'" + shuffle[x] + "'" + ","+ "'"+random.choice(Name) +"'"+
    ")" + ",")

('00000','Blanche','Mason',187,64.36,35,'F','Badminton','Thai','MM Sport'),
('00001','Alene','Perkins',151,83.36,23,'F','Football','Thai','Superman'),
('00002','Brady','Hotaling',151,84.3,24,'F','Basketball','Thai','Arm Sport'),
('00003','Joan','Gomez',151,47.05,38,'F','Basketball','Thai','MM Sport'),
('00004','Mary','Pitts',161,84.38,29,'F','PingPong','American','Man Uay FC'),
('00005','Julian','Murphy',182,98.94,19,'M','VolleyBall','Thai','Pheonix FC'),
('00006','Edna','Taylor',166,44.36,29,'F','Basketball','Korean','Beyonder'),
('00007','Delphine','Cogliano',198,47.25,32,'F','VolleyBall','Thai','GG Sport'),
('00008','Billy','Squier',150,52.03,37,'M','Boxing','Thai','Pheonix FC'),
('00009','Thomas','Clayton',162,72.76,32,'F','Athletic','Thai','KingKong Sport'),
('00010','Edward','Breeden',165,95.03,44,'F','PingPong','Thai','Man Uay FC'),
('00011','Michael','Cannon',199,45.29,43,'M','VolleyBall','Thai','Beyonder'),
('00012','Georgette','Wellington',176,66.0,21,'M','PingPong','Thai','MM Sport'),
('00013','Lawrence','Matesic',190,64.06,26,'M','PingPong','Thai','GG Sport'),
('00014','George','Abrial',183,69.05,35,'M','Athletic','Thai','GD Sport'),
('00015','Matthew','Mcneal',194,74.88,23,'M','Basketball','Thai','FairPlay Sport'),
('00016','Jason','Sartor',157,80.87,27,'F','Tennis','Thai','GG Sport'),
('00017','Beulah','Sakai',196,58.45,23,'F','Badminton','Thai','GD Sport'),
('00018','Maria','Kim',166,95.85,23,'M','Tennis','Thai','Underdogs Sport'),
('00019','Tamara','Ray',171,62.48,30,'F','VolleyBall','Thai','GD Sport'),
('00020','Monica','Bembry',200,75.47,29,'F','VolleyBall','Thai','Mahidol Sport'),
('00021','Raymond','Wing',154,99.7,40,'F','PingPong','Thai','Beyonder'),
('00022','Betty','Camper',170,95.72,16,'M','Badminton','Thai','KingKong Sport'),
('00023','Charles','Rocha',194,72.59,19,'F','PingPong','Thai','Big Boom FC'),
('00024','Thomas','Stuckett',188,92.37,40,'F','PingPong','Thai','MM Sport'),
('00025','Maggie','Archibald',189,70.54,31,'F','Tennis','Thai','FairPlay Sport'),
('00026','Lisa','Ross',164,87.19,29,'M','Boxing','Thai','The Best Team'),
('00027','Crystal','Beauchamp',167,67.69,45,'M','Basketball','Thai','GG Sport'),
('00028','Anthony','Corsaut',161,78.72,30,'M','Athletic','Thai','GG Sport'),
('00029','Alejandra','Stiltner',158,89.62,37,'M','Badminton','Thai','Beyonder'),
('00030','Jaime','Fox',158,84.51,31,'F','Tennis','Thai','GG Sport'),
('00031','Lindsay','Sentell',165,66.75,22,'F','Athletic','Thai','Easy Team'),
('00032','Roxann','Singley',151,64.9,39,'F','VolleyBall','Thai','Mahidol Sport'),
('00033','Chad','Nall',153,59.93,28,'M','Basketball','Thai','KingKong Sport'),
('00034','Christopher','Harman',177,68.69,36,'M','Badminton','Thai','Rich Kid'),
('00035','William','Young',172,94.32,21,'M','Tennis','Thai','Man Uay FC'),
('00036','Barbara','Taylor',160,91.35,22,'F','Basketball','Thai','Big Boom FC'),
('00037','Erika','Williams',171,43.84,42,'M','Tennis','Thai','Green Sport'),
('00038','Gail','Thomas',173,72.8,16,'M','Athletic','German','Uefa191'),
('00039','Marion','Czelusniak',164,85.35,28,'M','Boxing','Canadian','Rich Kid'),
('00040','Benjamin','Cowan',168,60.09,39,'F','Athletic','Thai','CC Sport'),
('00041','Sterling','Griffith',187,53.42,33,'F','Badminton','Thai','Arm Sport'),
('00042','Holly','Thornton',159,52.87,38,'F','Basketball','Thai','Uefa191'),
('00043','Olga','Shively',160,62.32,39,'F','Boxing','Thai','GD Sport'),
('00044','Shirley','Lehman',195,83.03,29,'F','VolleyBall','Thai','Beyonder'),
('00045','Anthony','Zacarias',196,49.03,31,'M','Boxing','Thai','Mahidol Sport'),
('00046','Nathan','Janosko',189,45.25,42,'F','Football','Italian','Good Team'),
('00047','Ted','Peel',178,82.99,15,'M','Tennis','Thai','Superman'),
('00048','Keith','Davis',199,47.39,20,'F','Boxing','Thai','GD Sport'),
('00049','Paula','Strider',167,92.45,37,'F','Basketball','Thai','Rich Kid'),
('00050','Anne','Gray',156,68.77,16,'F','Boxing','Thai','Good Team'),
('00051','Virgie','Mclain',150,81.67,29,'M','Tennis','Thai','Underdogs Sport'),
('00052','Morgan','Morosow',167,55.96,21,'F','VolleyBall','German','Man Uay FC'),
('00053','Susan','Kabel',186,87.83,31,'F','Athletic','Thai','Mahidol Sport'),
('00054','Angela','Debem',188,98.92,24,'M','VolleyBall','Canadian','ICT Sport'),
('00055','John','Haubrich',185,57.72,15,'M','Badminton','Thai','Rama Sport'),
('00056','Nettie','Sherman',199,82.66,19,'M','Football','Thai','Beyonder'),
('00057','David','Hewitt',169,76.08,42,'F','Badminton','Thai','ICT Sport'),
('00058','Karen','Piccoli',161,81.79,28,'F','Athletic','Thai','KingKong Sport'),
('00059','Carol','Starkey',173,75.06,25,'F','VolleyBall','Thai','Rich Kid'),
('00060','Dolores','Mcginness',188,66.63,45,'M','Tennis','Thai','Rama Sport'),
('00061','Irene','Mcquiston',176,61.72,27,'F','Tennis','Thai','Superman'),
('00062','Andrew','Odom',170,73.41,40,'M','Athletic','Thai','Arm Sport'),
('00063','Renee','Toy',163,46.91,16,'F','Boxing','Thai','Green Velvet'),
('00064','Claudette','Donaldson',157,48.26,29,'F','Athletic','Thai','Rama Sport'),
('00065','Michael','Nailor',166,50.93,45,'M','Tennis','Thai','KingKong Sport'),
('00066','Barbara','Turpin',176,75.07,35,'M','Boxing','Thai','Pheonix FC'),
('00067','Charley','Willis',183,72.91,33,'M','PingPong','Thai','Arm Sport'),
('00068','Dolores','Sharp',198,53.66,19,'F','Boxing','German','GD Sport'),
('00069','Mabel','Landers',188,46.8,25,'M','Basketball','Thai','Pheonix FC'),
('00070','Tyler','Henson',161,66.44,23,'M','Tennis','Thai','Rich Kid'),
('00071','Lillian','Honeycutt',200,74.19,44,'M','PingPong','Thai','Big Boom FC'),
('00072','Margherita','Jett',167,93.74,25,'F','Athletic','Thai','Mahidol Sport'),
('00073','Keith','Ouellette',168,49.61,37,'F','VolleyBall','Thai','MM Sport'),
('00074','Cindy','Zapata',186,88.42,31,'M','Boxing','Thai','The Best Team'),
('00075','George','Arnold',183,41.63,26,'F','Badminton','Thai','Batman Sport'),
('00076','Ethelyn','Putnam',188,81.68,17,'M','Football','Thai','XX Sport'),
('00077','Mary','Terry',177,52.96,40,'M','Boxing','Korean','Mahidol Sport'),
('00078','Lena','Labrum',190,99.04,28,'M','Athletic','Thai','ICT Sport'),
('00079','Erasmo','Price',183,49.83,22,'F','PingPong','Thai','Beyonder'),
('00080','Herman','Airington',169,40.37,38,'M','Athletic','Thai','MM Sport'),
('00081','Gregory','Torres',176,58.31,43,'F','Badminton','Canadian','Green Velvet'),
('00082','David','Leon',177,79.34,25,'F','Tennis','German','Green Velvet'),
('00083','Roy','Mix',189,43.59,37,'F','Boxing','Canadian','Man Uay FC'),
('00084','Mary','Reid',161,80.96,18,'F','Badminton','Thai','CC Sport'),
('00085','Laurel','Engler',200,52.66,20,'M','PingPong','Thai','CC Sport'),
('00086','Carroll','Johansen',172,92.49,33,'F','VolleyBall','Thai','FairPlay Sport'),
('00087','Mariam','Frank',191,62.82,30,'M','VolleyBall','Thai','CC Sport'),
('00088','Norma','Vanwagner',152,76.61,29,'F','Badminton','Thai','XX Sport'),
('00089','Naomi','Runion',150,82.53,21,'F','PingPong','Thai','Pheonix FC'),
('00090','Melvin','Andre',190,58.85,29,'F','Football','Thai','Uefa191'),
('00091','Crystal','Newell',173,43.28,29,'M','VolleyBall','Thai','The Best Team'),
('00092','Derrick','Gorby',158,86.97,15,'F','PingPong','Thai','Rich Kid'),
('00093','Melissa','Parker',199,57.74,37,'F','VolleyBall','Thai','One Above All'),
('00094','Casey','Johnson',158,70.9,39,'M','Boxing','Thai','Batman Sport'),
('00095','Rachel','Barnes',171,45.94,23,'M','Badminton','Thai','The Best Team'),
('00096','Kristen','Smith',198,93.66,29,'M','VolleyBall','Thai','Batman Sport'),
('00097','Glenna','Mueller',158,74.48,42,'M','Tennis','German','Superman'),
('00098','Roger','Aguilar',175,91.54,29,'M','Athletic','Thai','Superman'),
('00099','Cleveland','Miller',188,48.96,43,'M','VolleyBall','Thai','FairPlay Sport'),
('00100','Marcus','Baker',198,41.43,37,'F','Tennis','Thai','One Above All'),
('00101','Charlie','Taylor',191,97.02,33,'F','PingPong','Thai','One Above All'),
('00102','Danny','Dew',167,88.08,23,'M','VolleyBall','Thai','Rich Kid'),
('00103','Steven','Arnold',156,84.18,37,'F','Football','Thai','Arm Sport'),
('00104','Rose','Cook',185,91.72,29,'F','Tennis','Thai','Green Velvet'),
('00105','Beverly','Adrian',172,90.28,30,'F','VolleyBall','Korean','ICT Sport'),
('00106','Anthony','Griffin',189,90.27,38,'M','Boxing','Thai','Big Boom FC'),
('00107','John','Chi',192,50.72,40,'M','Athletic','Thai','Underdogs Sport'),
('00108','Joyce','Messina',196,79.54,15,'M','Boxing','Thai','Man Uay FC'),
('00109','Louise','Gonzalas',153,75.03,34,'F','Football','Thai','Underdogs Sport'),
('00110','Sara','Montoya',177,85.08,34,'M','Basketball','Thai','Easy Team'),
('00111','Rebeca','Engebretson',188,79.63,27,'M','PingPong','Thai','The Best Team'),
('00112','John','Shoe',164,71.71,45,'F','Football','Thai','MM Sport'),
('00113','George','Chauvin',167,84.52,45,'F','Tennis','Thai','Superman'),
('00114','Shirley','Price',175,85.62,35,'M','Football','Thai','Big Boom FC'),
('00115','Charles','Robertson',163,45.12,24,'F','Tennis','Thai','Pheonix FC'),
('00116','Maria','Hines',199,70.97,20,'F','Badminton','Thai','FairPlay Sport'),
('00117','Amber','Lank',151,58.62,19,'M','VolleyBall','Thai','GG Sport'),
('00118','Ashley','Garcia',182,70.89,22,'F','PingPong','Thai','Big Boom FC'),
('00119','Jerry','Mansfield',167,60.24,36,'M','Badminton','Canadian','Underdogs Sport'),
('00120','Frank','Donaldson',168,99.21,29,'F','PingPong','Thai','Green Velvet'),
('00121','Brenda','Luck',190,44.34,39,'M','Boxing','Thai','Rich Kid'),
('00122','Sadie','Brown',189,78.94,33,'M','Athletic','Korean','Green Sport'),
('00123','Cynthia','Bollig',165,80.77,19,'M','Football','Thai','Uefa191'),
('00124','Delores','Cain',179,93.03,36,'M','PingPong','Thai','Superman'),
('00125','Kevin','Doughty',160,85.05,31,'M','Badminton','Japanese','Rama Sport'),
('00126','Melissa','Atkinson',152,49.88,35,'M','PingPong','Thai','Batman Sport'),
('00127','Ferne','Carroll',193,93.79,40,'M','PingPong','Thai','ICT Sport'),
('00128','Joseph','Henderson',188,84.52,43,'F','Athletic','Thai','Big Boom FC'),
('00129','Richard','Gonzales',198,89.8,21,'M','Tennis','Thai','Mahidol Sport'),
('00130','Tandy','Zien',193,45.57,33,'M','Badminton','Thai','FairPlay Sport'),
('00131','Elizabeth','Brown',192,76.96,40,'F','Boxing','Thai','Green Sport'),
('00132','Ginger','Oliver',186,45.48,36,'F','Badminton','Thai','GD Sport'),
('00133','Kathy','Pittman',160,59.58,18,'F','Badminton','Thai','One Above All'),
('00134','Robert','Bell',151,68.65,22,'M','Football','Thai','Uefa191'),
('00135','Matthew','Boykin',165,74.41,20,'F','Boxing','German','Beyonder'),
('00136','Katherine','Gonzalez',179,71.82,41,'M','Athletic','Thai','GD Sport'),
('00137','Benedict','Weaver',173,86.38,15,'M','PingPong','Japanese','Green Velvet'),
('00138','Elaine','Walston',181,67.33,25,'M','PingPong','Thai','Beyonder'),
('00139','Fairy','Blackshear',152,81.24,43,'M','PingPong','Thai','Superman'),
('00140','Douglas','Ancheta',199,76.0,22,'F','VolleyBall','Thai','KingKong Sport'),
('00141','Charles','Warner',173,88.55,21,'F','Boxing','Thai','One Above All'),
('00142','Michael','Yarbrough',191,75.95,45,'F','VolleyBall','Thai','Easy Team'),
('00143','Raymond','Orlando',191,47.07,22,'M','Badminton','Thai','Mahidol Sport'),
('00144','Rita','Demers',184,77.31,44,'F','Basketball','Thai','Uefa191'),
('00145','Karen','Thomas',197,87.58,26,'M','Boxing','Thai','GG Sport'),
('00146','George','Mcdonald',163,79.68,32,'M','Basketball','Thai','Big Boom FC'),
('00147','Virginia','Hoover',176,50.21,25,'F','Tennis','Thai','KingKong Sport'),
('00148','Christopher','Fenn',174,42.62,35,'F','Tennis','Thai','Superman'),
('00149','Esther','Steele',183,97.14,16,'F','Tennis','Thai','Good Team'),
('00150','Daniel','Jensen',171,94.15,32,'F','Football','Thai','Arm Sport'),
('00151','Muriel','Barrow',183,61.6,38,'M','PingPong','Thai','Green Velvet'),
('00152','Gary','Cole',169,90.35,32,'M','Football','Thai','Pheonix FC'),
('00153','Lawrence','Beatty',153,46.89,28,'F','Badminton','Thai','CC Sport'),
('00154','Ronald','Carrillo',198,43.05,21,'M','Basketball','Thai','Underdogs Sport'),
('00155','Susan','Penner',158,89.23,34,'M','Boxing','Korean','One Above All'),
('00156','Regina','August',174,67.14,39,'F','Football','Thai','GD Sport'),
('00157','Lelia','Gorrell',165,68.31,20,'M','Badminton','Thai','Mahidol Sport'),
('00158','Delores','Henry',199,61.46,18,'M','Tennis','Canadian','Batman Sport'),
('00159','John','Bradley',190,44.32,42,'F','Tennis','Thai','Easy Team'),
('00160','Carla','Comeau',171,60.66,33,'M','Football','Thai','Batman Sport'),
('00161','Maurice','Rodgers',183,97.14,38,'M','PingPong','Thai','Good Team'),
('00162','Michael','Galloway',150,67.38,30,'F','PingPong','Thai','KingKong Sport'),
('00163','Anthony','Cone',163,75.04,45,'F','Boxing','Thai','Beyonder'),
('00164','Patricia','Jamison',156,85.43,40,'F','Badminton','Thai','Superman'),
('00165','Jessica','Cunningham',152,62.51,29,'M','Boxing','Thai','Green Velvet'),
('00166','James','Matthew',159,79.83,44,'M','Basketball','Thai','FairPlay Sport'),
('00167','Richard','Ross',151,41.8,44,'M','Tennis','German','The Best Team'),
('00168','Rosalie','Stellhorn',172,95.08,34,'F','Basketball','Thai','Rich Kid'),
('00169','Kristy','Brendel',154,81.19,26,'M','Tennis','Thai','One Above All'),
('00170','Kara','Dominguez',172,82.84,40,'F','Tennis','Thai','Rama Sport'),
('00171','Berneice','Bonner',187,46.18,37,'M','Tennis','Thai','The Best Team'),
('00172','Thelma','Everett',195,53.49,34,'M','Basketball','Thai','Man Uay FC'),
('00173','Barbara','Winters',187,67.89,29,'F','PingPong','Korean','Big Boom FC'),
('00174','Barbara','Vantassel',171,81.87,35,'F','Athletic','Korean','Man Uay FC'),
('00175','Sherry','Carey',170,43.71,36,'M','PingPong','Thai','KingKong Sport'),
('00176','James','Stroman',160,68.87,34,'M','VolleyBall','Thai','Mahidol Sport'),
('00177','Sanford','Ervin',173,53.92,41,'M','Badminton','Thai','Easy Team'),
('00178','Kathy','Aubin',172,76.56,34,'M','Football','Thai','Arm Sport'),
('00179','Lyle','Sparks',171,58.57,17,'F','VolleyBall','Thai','MM Sport'),
('00180','Mary','Sumpter',151,66.82,40,'F','Football','German','Good Team'),
('00181','Jose','Costa',199,41.47,20,'M','Badminton','Thai','ICT Sport'),
('00182','Derek','Maxfield',169,47.09,39,'M','Badminton','Thai','Pheonix FC'),
('00183','Kris','Wilson',150,98.74,22,'M','Football','Korean','MM Sport'),
('00184','Ellis','Plues',151,56.53,42,'F','Boxing','Thai','KingKong Sport'),
('00185','Darrin','Stephens',194,63.42,39,'F','Football','Thai','FairPlay Sport'),
('00186','Melvin','Campbell',180,78.44,31,'F','PingPong','Thai','Underdogs Sport'),
('00187','Rosemary','Bruce',163,75.14,19,'M','Boxing','Thai','Uefa191'),
('00188','Stephanie','Blake',187,54.73,44,'M','PingPong','Thai','Underdogs Sport'),
('00189','Barbara','Johnson',164,99.44,33,'M','Football','Thai','Rich Kid'),
('00190','Pamela','Nester',178,47.83,26,'M','PingPong','Thai','Beyonder'),
('00191','Christopher','Belin',183,50.8,21,'M','Tennis','Thai','XX Sport'),
('00192','Rolando','Johnson',167,80.93,17,'M','Tennis','Thai','The Best Team'),
('00193','David','Castleberry',153,58.18,19,'F','VolleyBall','Thai','Easy Team'),
('00194','Claudia','Shaw',197,86.34,43,'M','PingPong','Thai','FairPlay Sport'),
('00195','Jamie','Fulmer',177,65.05,16,'M','Basketball','Thai','Green Sport'),
('00196','Pamela','Landry',198,63.9,17,'F','Basketball','Thai','Easy Team'),
('00197','Cathrine','Nielsen',151,75.0,21,'F','Boxing','American','Mahidol Sport'),
('00198','Desiree','Osborne',178,41.62,37,'M','Basketball','Canadian','The Best Team'),
('00199','Johnny','Metzger',200,64.05,42,'M','Athletic','Thai','Green Velvet'),
('00200','Lester','Dugas',155,79.18,27,'F','Basketball','Canadian','Uefa191'),
('00201','Teresa','Williams',195,45.19,40,'F','Tennis','Thai','Underdogs Sport'),
('00202','Mark','Solomen',151,48.03,26,'M','Badminton','Thai','XX Sport'),
('00203','Thelma','Mitchell',171,99.91,28,'F','VolleyBall','Thai','Arm Sport'),
('00204','Elwood','Cornett',171,95.82,41,'F','Athletic','Thai','ICT Sport'),
('00205','Mary','Jones',180,90.97,25,'F','Athletic','Thai','MM Sport'),
('00206','Larry','Mauldin',170,99.43,39,'F','VolleyBall','Thai','ICT Sport'),
('00207','John','Victor',179,99.22,39,'F','Basketball','Thai','Underdogs Sport'),
('00208','Alton','Trotter',196,82.41,21,'M','VolleyBall','Thai','Green Velvet'),
('00209','Louie','Dunham',175,95.78,41,'F','Badminton','Thai','Big Boom FC'),
('00210','Meredith','Johnson',191,48.35,43,'F','PingPong','Korean','Mahidol Sport'),
('00211','Zachary','Hawkins',172,93.3,19,'F','Boxing','Korean','MM Sport'),
('00212','Derrick','Ross',179,85.41,41,'M','Tennis','Thai','Rich Kid'),
('00213','John','Hux',151,60.41,33,'F','Basketball','Thai','GG Sport'),
('00214','Charles','Chapin',153,70.58,17,'M','Boxing','Thai','FairPlay Sport'),
('00215','Sharon','Koster',150,82.76,27,'M','Athletic','Thai','GD Sport'),
('00216','Edward','Ramsey',172,46.57,29,'M','Boxing','Thai','The Best Team'),
('00217','Patricia','Howard',170,99.76,38,'F','VolleyBall','Thai','Underdogs Sport'),
('00218','William','Portz',166,91.02,32,'M','PingPong','Thai','GD Sport'),
('00219','Annette','Epperson',160,62.92,33,'F','Football','Thai','Arm Sport'),
('00220','Ralph','Rappold',150,58.49,31,'F','Tennis','Thai','ICT Sport'),
('00221','Linda','Martin',150,56.52,33,'F','Boxing','Thai','Batman Sport'),
('00222','Regenia','Froneberger',196,81.88,44,'M','VolleyBall','Thai','Batman Sport'),
('00223','Dawn','Whitehurst',200,49.51,27,'M','Tennis','Thai','Uefa191'),
('00224','Kathleen','Crane',183,89.38,39,'M','VolleyBall','Thai','Batman Sport'),
('00225','Nancy','Butler',154,67.59,30,'F','PingPong','German','MM Sport'),
('00226','James','Fabrizio',154,94.44,19,'F','Football','Thai','Beyonder'),
('00227','Anita','Santos',197,78.23,45,'M','Badminton','Thai','Good Team'),
('00228','Joseph','Martinez',185,84.86,35,'M','Boxing','Thai','One Above All'),
('00229','John','Williamson',183,81.47,42,'F','VolleyBall','Thai','Man Uay FC'),
('00230','Rick','Paynter',160,92.52,34,'F','Tennis','Thai','Uefa191'),
('00231','Daisy','Duprey',159,85.95,22,'M','VolleyBall','Thai','Underdogs Sport'),
('00232','Patrica','Angle',166,84.16,28,'M','Football','Korean','Good Team'),
('00233','Grover','Walker',157,97.24,37,'M','VolleyBall','Thai','Mahidol Sport'),
('00234','Jonathan','Scarborough',190,65.19,32,'M','VolleyBall','German','GG Sport'),
('00235','Frank','Kapinos',162,71.32,20,'M','Boxing','Thai','Rama Sport'),
('00236','Timothy','Hunter',153,99.98,29,'M','Athletic','Korean','XX Sport'),
('00237','Martha','Smit',200,86.23,34,'M','Athletic','Thai','Rich Kid'),
('00238','Joseph','Coleman',185,60.81,29,'F','Boxing','Thai','MM Sport'),
('00239','Louis','Burns',165,92.12,37,'F','Tennis','Thai','Man Uay FC'),
('00240','Leonard','Cannon',160,61.17,19,'M','Athletic','Thai','Rama Sport'),
('00241','Domenica','Erskine',151,73.95,40,'M','Badminton','Thai','Man Uay FC'),
('00242','Luis','Hester',170,59.14,42,'M','Badminton','Thai','Green Sport'),
('00243','Edna','Lu',188,85.17,45,'F','Football','Thai','Green Sport'),
('00244','Arthur','Frick',178,69.22,25,'M','Boxing','Thai','Superman'),
('00245','Patricia','Young',162,83.3,43,'M','Basketball','Thai','Rama Sport'),
('00246','Leah','Simpson',167,72.25,20,'M','Tennis','Thai','Green Sport'),
('00247','Mary','Reed',190,61.83,31,'F','Badminton','Thai','Batman Sport'),
('00248','Georgia','Bickford',159,87.78,19,'M','Basketball','Thai','Arm Sport'),
('00249','Deborah','Davis',158,66.36,40,'F','Athletic','Thai','XX Sport'),
('00250','Scott','Brennan',161,40.53,45,'F','VolleyBall','Thai','Man Uay FC'),
('00251','Roxanne','Hoar',200,82.1,35,'M','Basketball','Thai','Green Sport'),
('00252','David','Bond',194,41.56,17,'F','Athletic','Thai','FairPlay Sport'),
('00253','Robert','Powell',186,98.74,37,'F','Athletic','Thai','Beyonder'),
('00254','Etta','Wordlaw',195,43.0,20,'F','Boxing','Thai','Big Boom FC'),
('00255','Audrey','Dwyer',163,99.21,23,'F','PingPong','Thai','Superman'),

In [8]:
atlist = []
for x in range(0,athlete):
    atlist.append([str(x).zfill(5),names.get_first_name(),names.get_last_name(),str(random.randint(150,200)),str(round(random.uniform(40,100),2)),str(random.randint(15,45)),random.choice(gender),
                    random.choice(sport_type), shuffle[x], random.choice(Name)])

In [9]:
atdf = pd.DataFrame(atlist, columns = ['Athlete_ID', 'FirstName','LastName','Ath_Height','Ath_Weight','Age','Gender','Sport_Type','Nationality','Team_Name'])

In [13]:
atdf

,Athlete_ID,FirstName,LastName,Ath_Height,Ath_Weight,Age,Gender,Sport_Type,Nationality,Team_Name
0,00000,Lucrecia,Delbridge,181,56.05,45,M,Boxing,Thai,Pheonix FC
1,00001,Seth,Harris,172,84.94,25,M,VolleyBall,Thai,Underdogs Sport
2,00002,Janice,Rodriguez,180,77.61,32,M,Basketball,Thai,GG Sport
3,00003,Margaret,Tullar,179,71.47,27,M,Boxing,Thai,The Best Team
4,00004,Felix,Smith,198,51.59,19,M,Basketball,Thai,FairPlay Sport
...,...,...,...,...,...,...,...,...,...,...
995,00995,Cameron,Ratermann,189,55.33,19,F,PingPong,Korean,Man Uay FC
996,00996,Anne,Staples,173,87.99,23,M,Athletic,Canadian,Uefa191
997,00997,Michael,Collins,182,72.3,15,F,Boxing,Thai,Mahidol Sport
998,00998,Hazel,Truax,195,60.0,20,F,PingPong,Thai,Underdogs Sport
999,00999,Lloyd,White,161,65.38,34,F,Tennis,Thai,Green Velvet

In [17]:
start_date = datetime.date(1970, 2, 14)
end_date = datetime.date(2020, 1, 1)

In [16]:
for x in range(0,team +1):
    
    time_between_dates = end_date - start_date
    days_between_dates = time_between_dates.days
    random_number_of_days = random.randrange(days_between_dates)
    random_date = start_date + datetime.timedelta(days=random_number_of_days)
    print("("
     + "'"+ Name[x] + "'" + "," + "'" + random.choice(sport_type) + "'" + ","  + "'" + str(random_date) + "'"+ 
    ")" + ",")

('Mahidol Sport','Basketball','2001-12-19'),
('ICT Sport','Basketball','2017-04-05'),
('KingKong Sport','Football','1981-03-10'),
('Arm Sport','Basketball','2005-11-06'),
('GD Sport','Boxing','2000-08-24'),
('Underdogs Sport','Boxing','2002-10-22'),
('Man Uay FC','VolleyBall','1984-12-18'),
('Big Boom FC','PingPong','1970-05-14'),
('Easy Team','PingPong','1971-04-08'),
('Uefa191','Boxing','1999-08-08'),
('CC Sport','Basketball','1997-06-23'),
('Good Team','Basketball','1995-06-25'),
('Pheonix FC','Football','1984-05-12'),
('Green Sport','Basketball','2002-12-01'),
('FairPlay Sport','VolleyBall','1990-11-18'),
('The Best Team','Tennis','2003-03-21'),
('Beyonder','Athletic','1994-05-12'),
('One Above All','PingPong','2014-06-14'),
('Superman','Tennis','1987-12-04'),
('Batman Sport','Football','1985-03-07'),
('Rich Kid','Athletic','2003-03-09'),
('GG Sport','Tennis','1977-12-23'),
('XX Sport','Tennis','1973-01-31'),
('Rama Sport','PingPong','1985-01-01'),
('MM Sport','VolleyBall','1998-06-07'),
('Green Velvet','PingPong','1973-09-28'),

In [19]:
teamlist = []
for x in range(0,team +1):
    time_between_dates = end_date - start_date
    days_between_dates = time_between_dates.days
    random_number_of_days = random.randrange(days_between_dates)
    random_date = start_date + datetime.timedelta(days=random_number_of_days)
    teamlist.append([Name[x],random.choice(sport_type),str(random_date)])

In [20]:
teamdf = pd.DataFrame(teamlist, columns = ['Team_Name','Type_Of_Sport','Founded_Date'])

In [21]:
teamdf

          Team_Name Type_Of_Sport Founded_Date
0     Mahidol Sport      PingPong   1984-11-25
1         ICT Sport     Badminton   1993-01-27
2    KingKong Sport     Badminton   2018-01-17
3         Arm Sport        Boxing   2013-09-07
4          GD Sport      Athletic   1983-02-26
5   Underdogs Sport      PingPong   1975-04-15
6        Man Uay FC        Boxing   1985-01-18
7       Big Boom FC      Football   2015-09-15
8         Easy Team        Tennis   1977-02-19
9           Uefa191      Football   2016-11-20
10         CC Sport     Badminton   1985-07-29
11        Good Team        Tennis   1995-10-10
12       Pheonix FC    Basketball   1999-09-02
13      Green Sport        Tennis   1994-03-22
14   FairPlay Sport        Boxing   1998-04-24
15    The Best Team    Basketball   1984-10-03
16         Beyonder      PingPong   1985-08-23
17    One Above All    Basketball   1991-02-01
18         Superman     Badminton   1991-12-28
19     Batman Sport      Athletic   1995-08-22
20         Rich Kid     Badminton   1992-12-18
21         GG Sport      Football   1974-10-29
22         XX Sport      PingPong   2019-05-03
23       Rama Sport        Tennis   1999-07-21
24         MM Sport      Football   2015-12-24
25     Green Velvet    Basketball   2016-10-22

In [22]:
medical = 70
Branch = ["Ophthalmologists","Neurologists","Nephrologists","Internists","Hematologists","Endocrinologists","Dermatologists","Critical Care Medicine Specialists","Cardiologists",
            "Psycologist"]
staff = []

# for i in range(0,40):
#     first = "0"+ str(random.randint(80,93))
#     second = str(random.randint(0,999)).zfill(3)
#     third = str(random.randint(0,9999)).zfill(4)
#     print(first + "-" + second+ "-" + third)
# for x in range(0,70):
#     first = "0"+ str(random.randint(80,93))
#     second = str(random.randint(0,999)).zfill(3)
#     third = str(random.randint(0,9999)).zfill(4)
#     staff.append("("
#      + "'" + str(x).zfill(5) +  "'" +"," + "'" + names.get_first_name()+"'"  +"," + "'" + names.get_last_name()+ "'" + "," + "'" + random.choice(Branch) + "'"+  "," + 
#      "'" +"Assistant"+ "'" +"," + "'" + first + "-" + second+ "-" + third + "'"+
#     ")" + ",")

medicallist = []

for x in range(0,70):
    first = "0"+ str(random.randint(80,93))
    second = str(random.randint(0,999)).zfill(3)
    third = str(random.randint(0,9999)).zfill(4)
    medicallist.append([str(x).zfill(5),names.get_first_name(),names.get_last_name(),random.choice(Branch),"Assistant",first +'-' + second + "-" + third])

dfmedical = pd.DataFrame(medicallist, columns = ['Medical_Staff_ID','FirstName','LastName','Branch','Position','Phone'])

In [23]:
dfmedical

,Medical_Staff_ID,FirstName,LastName,Branch,Position,Phone
0,00000,Carmelita,Federico,Internists,Assistant,086-760-4853
1,00001,Brian,Wilkowitz,Hematologists,Assistant,085-387-8997
2,00002,Clarence,Cusack,Psycologist,Assistant,087-883-1751
3,00003,Kevin,Garica,Nephrologists,Assistant,082-850-7652
4,00004,Stephen,Harris,Internists,Assistant,082-316-0420
...,...,...,...,...,...,...
65,00065,Scott,Hipple,Internists,Assistant,089-798-8437
66,00066,Shantelle,Gunderman,Internists,Assistant,087-624-9706
67,00067,Tiffani,Pavlick,Endocrinologists,Assistant,082-049-5241
68,00068,Don,Trout,Endocrinologists,Assistant,093-309-2283
69,00069,Mark,Smith,Ophthalmologists,Assistant,093-936-8119

In [27]:
title = 'Ophthalmologists'
for i in range (0, len(staff)):
    if(title in staff[i]):
        print(staff[i])

('00004','Jerry','Moyes','Ophthalmologists','Assistant','087-511-1091'),
('00005','Patricia','Hubbard','Ophthalmologists','Assistant','091-623-6248'),
('00032','Marvin','Kern','Ophthalmologists','Assistant','082-427-4244'),
('00034','Henry','Caruso','Ophthalmologists','Assistant','088-612-3746'),
('00038','Pamela','Kendrick','Ophthalmologists','Assistant','088-519-2682'),
('00039','Christopher','Wolf','Ophthalmologists','Assistant','086-762-3818'),
('00041','Josephine','Cirrincione','Ophthalmologists','Assistant','091-880-8683'),
('00044','Arlene','Daniels','Ophthalmologists','Assistant','087-187-9473'),
('00049','John','Parrish','Ophthalmologists','Assistant','086-530-5960'),
('00051','Stephen','Esparza','Ophthalmologists','Assistant','089-945-6390'),
('00057','Georgia','Brunet','Ophthalmologists','Assistant','083-561-9115'),
('00065','Mary','Diberardino','Ophthalmologists','Assistant','087-322-8549'),

In [28]:
for i in range(0,70):
    print(staff[i])

('00000','Velma','Williams','Endocrinologists','Assistant','082-760-3241'),
('00001','Richard','Avila','Cardiologists','Assistant','088-613-4492'),
('00002','Douglas','Wilson','Critical Care Medicine Specialists','Assistant','082-134-8047'),
('00003','Kenneth','Pittman','Cardiologists','Assistant','081-491-3497'),
('00004','Jerry','Moyes','Ophthalmologists','Assistant','087-511-1091'),
('00005','Patricia','Hubbard','Ophthalmologists','Assistant','091-623-6248'),
('00006','Hattie','Seales','Neurologists','Assistant','082-168-7487'),
('00007','Melissa','Duvall','Critical Care Medicine Specialists','Assistant','083-107-9862'),
('00008','Alvin','Sedillo','Nephrologists','Assistant','087-166-3376'),
('00009','Natalie','Shannon','Endocrinologists','Assistant','085-820-8588'),
('00010','Howard','Cole','Neurologists','Assistant','091-289-3347'),
('00011','Mike','Reeder','Hematologists','Assistant','083-773-5934'),
('00012','Jarrod','Maguire','Hematologists','Assistant','090-609-9987'),
('00013','Dulcie','Mervis','Critical Care Medicine Specialists','Assistant','082-932-7239'),
('00014','Roger','Berrier','Cardiologists','Assistant','085-246-4096'),
('00015','Young','Vazquez','Critical Care Medicine Specialists','Assistant','087-489-0994'),
('00016','William','Keyt','Dermatologists','Assistant','088-785-4880'),
('00017','Shirley','Clark','Internists','Assistant','081-334-6502'),
('00018','Lucius','Macaluso','Dermatologists','Assistant','085-133-2251'),
('00019','Teresa','Hernandez','Critical Care Medicine Specialists','Assistant','081-679-6319'),
('00020','Patricia','Sutton','Nephrologists','Assistant','088-510-2351'),
('00021','Steven','Jenkins','Cardiologists','Assistant','083-696-3248'),
('00022','Thomas','Villarreal','Cardiologists','Assistant','082-651-9157'),
('00023','Matthew','Sprouse','Neurologists','Assistant','082-405-9481'),
('00024','Felisa','Elfrink','Nephrologists','Assistant','084-266-9317'),
('00025','Lisa','Cullen','Hematologists','Assistant','091-665-9161'),
('00026','Helen','Holder','Internists','Assistant','093-172-7853'),
('00027','Richard','Davidson','Cardiologists','Assistant','086-619-0178'),
('00028','Colleen','Cornwell','Internists','Assistant','085-992-4720'),
('00029','Opal','Hoffman','Internists','Assistant','087-309-4062'),
('00030','Lorraine','Grant','Nephrologists','Assistant','083-528-0750'),
('00031','Kevin','Nichols','Neurologists','Assistant','086-281-5342'),
('00032','Marvin','Kern','Ophthalmologists','Assistant','082-427-4244'),
('00033','Gordon','Gardner','Neurologists','Assistant','083-948-6561'),
('00034','Henry','Caruso','Ophthalmologists','Assistant','088-612-3746'),
('00035','Justin','Oneil','Psycologist','Assistant','080-462-8079'),
('00036','Leonor','Duncan','Neurologists','Assistant','082-959-6508'),
('00037','Benjamin','Snyder','Endocrinologists','Assistant','092-303-8999'),
('00038','Pamela','Kendrick','Ophthalmologists','Assistant','088-519-2682'),
('00039','Christopher','Wolf','Ophthalmologists','Assistant','086-762-3818'),
('00040','William','Allen','Neurologists','Assistant','087-237-9487'),
('00041','Josephine','Cirrincione','Ophthalmologists','Assistant','091-880-8683'),
('00042','Cody','Meza','Psycologist','Assistant','088-667-2726'),
('00043','James','Logsdon','Cardiologists','Assistant','082-763-5198'),
('00044','Arlene','Daniels','Ophthalmologists','Assistant','087-187-9473'),
('00045','Brian','Murphy','Neurologists','Assistant','085-261-2538'),
('00046','Charles','Madera','Endocrinologists','Assistant','080-437-6895'),
('00047','Chris','Jeronimo','Hematologists','Assistant','082-572-6181'),
('00048','Aaron','Hunderlach','Neurologists','Assistant','093-234-1129'),
('00049','John','Parrish','Ophthalmologists','Assistant','086-530-5960'),
('00050','Shelia','Allen','Neurologists','Assistant','082-176-2682'),
('00051','Stephen','Esparza','Ophthalmologists','Assistant','089-945-6390'),
('00052','Mary','Yarbrough','Nephrologists','Assistant','085-317-0141'),
('00053','William','Atwood','Neurologists','Assistant','084-865-6057'),
('00054','Eric','Randolph','Hematologists','Assistant','087-256-2267'),
('00055','Michele','Wright','Endocrinologists','Assistant','080-399-8497'),
('00056','Raymond','Cason','Neurologists','Assistant','086-762-8050'),
('00057','Georgia','Brunet','Ophthalmologists','Assistant','083-561-9115'),
('00058','Bernice','Williams','Neurologists','Assistant','083-060-3762'),
('00059','Rhonda','Metcalf','Internists','Assistant','091-590-4540'),
('00060','Matthew','Senn','Hematologists','Assistant','091-436-2248'),
('00061','Willis','Wilfong','Hematologists','Assistant','086-471-4321'),
('00062','Loretta','Basich','Critical Care Medicine Specialists','Assistant','091-914-9920'),
('00063','Julie','Miller','Hematologists','Assistant','087-697-1253'),
('00064','Leslie','Aponte','Dermatologists','Assistant','090-319-5856'),
('00065','Mary','Diberardino','Ophthalmologists','Assistant','087-322-8549'),
('00066','Alexis','Collins','Psycologist','Assistant','084-547-0500'),
('00067','Ashley','Gabrielson','Endocrinologists','Assistant','083-931-0898'),
('00068','Jennifer','Fager','Internists','Assistant','080-420-1152'),
('00069','Donald','Beverly','Critical Care Medicine Specialists','Assistant','082-047-7800'),

In [24]:
psycolist = []
num = 100
start_date = datetime.date(2021, 2, 14)
end_date = datetime.date(2021, 12, 1)

psyco_start = datetime.date(2021, 12, 2)
psyco_end = datetime.date(2022, 12, 14)


for x in range(0,num):
    time_between_dates = end_date - start_date
    days_between_dates = time_between_dates.days
    random_number_of_days = random.randrange(days_between_dates)
    random_date = start_date + datetime.timedelta(days=random_number_of_days)

    tb = psyco_end - psyco_start
    nextstep = tb.days
    nextstepp = random.randrange(nextstep)
    randomstep = psyco_start + datetime.timedelta(days=nextstepp)
    psycolist.append([str(x).zfill(5),str(random.randint(0,999)).zfill(5),str(random.randint(0,69)).zfill(5),str(random_date),str(random.randint(0,10)),str(round(random.uniform(0,100),2)),
                        str(round(random.uniform(0,10),2)), str(randomstep)])
    # print("("
    #  + "'" + str(x).zfill(5) +  "'" +"," + "'" + str(random.randint(0,999)).zfill(5) +"'" + "," + "'" + str(random.randint(0,69)).zfill(5)   + "'"+  "," + 
    #  "'" +str(random_date)+ "'" +"," + str(random.randint(0,10))+ ","+ str(round(random.uniform(0,100),2)) + "," +str(round(random.uniform(0,10),2))  +","+ "'" +str(randomstep)
    #  + "'"+
    # ")" + ",")

In [25]:
psycodf = pd.DataFrame(psycolist, columns=['Psyco_ID','Athlete_ID','Medical_Staff_ID','Recovery_Started_Date','Sleep_Quality','I_PRRS_Score','VAS_F','Recovery_Ended_Date'])

In [26]:
psycodf

,Psyco_ID,Athlete_ID,Medical_Staff_ID,Recovery_Started_Date,Sleep_Quality,I_PRRS_Score,VAS_F,Recovery_Ended_Date
0,00000,00593,00051,2021-08-28,2,90.15,3.07,2022-09-04
1,00001,00929,00069,2021-06-04,5,79.72,6.28,2022-04-09
2,00002,00260,00050,2021-04-27,7,35.16,2.86,2022-04-08
3,00003,00632,00063,2021-09-21,10,18.46,7.14,2022-04-06
4,00004,00563,00009,2021-10-21,2,88.38,4.37,2022-02-28
...,...,...,...,...,...,...,...,...
95,00095,00823,00015,2021-10-04,2,43.84,6.66,2022-05-12
96,00096,00259,00063,2021-08-08,0,82.16,8.18,2022-03-29
97,00097,00447,00008,2021-02-17,3,68.34,1.74,2022-04-02
98,00098,00844,00046,2021-03-22,0,77.94,6.95,2022-07-27
99,00099,00591,00054,2021-07-16,0,20.08,5.76,2022-10-27

In [27]:
injurylist = []
num = 100
start_date = datetime.date(2021, 2, 14)
end_date = datetime.date(2021, 12, 1)

psyco_start = datetime.date(2021, 12, 2)
psyco_end = datetime.date(2022, 12, 14)

event = ["During the match", "After the match", "During Training", "After Training","While Sleeping", "Daily Life Accident"]
Body_part = ["Left Arm","Right Arm","Chest","Left Hand","Right Hand","Right Leg","Left Leg","Right Foot","Left Foot","Skull","Back","Shoulder","Immune System" , "Brain","Right Eye",
            "Left Eye","Heart","Stomach","Nose","Teeth","Mouth","Face"]
cause = ["Tackle","Effect after the training or match","Body System Failure","Daily Accident"]

for x in range(0,num):
    time_between_dates = end_date - start_date
    days_between_dates = time_between_dates.days
    random_number_of_days = random.randrange(days_between_dates)
    random_date = start_date + datetime.timedelta(days=random_number_of_days)

    tb = psyco_end - psyco_start
    nextstep = tb.days
    nextstepp = random.randrange(nextstep)
    randomstep = psyco_start + datetime.timedelta(days=nextstepp)
    injurylist.append([str(x).zfill(5),str(random.randint(0,999)).zfill(5),str(random.randint(0,69)).zfill(5),str(random_date),str(random.choice(event)),str(random.choice(Body_part)),str(random.randint(1,6)),
                        str(random.choice(cause)),str(randomstep)])
    # print("("
    #  + "'" + str(x).zfill(5) +  "'" +"," + "'" + str(random.randint(0,999)).zfill(5) +"'" + "," + "'" + str(random.randint(0,69)).zfill(5)   + "'"+  "," + 
    #  "'" +str(random_date)+ "'" +"," + "'" + str(random.choice(event)) + "'" + "," +"'" + str(random.choice(Body_part))+ "'"+ "," + str(random.randint(1,6)) +","
    #  "'" + str(random.choice(cause))+ "'" + ","+ "'" +str(randomstep)+ "'"+
    # ")" + ",")

In [29]:
injurydf = pd.DataFrame(injurylist, columns=['Injury_ID','Athlete_ID','Medical_Staff_ID','Recovery_Started_Date','Event_Injury','Body_Part','Abbreviated_Injury_Scale','Cause_Of_Injury','Recovery_Ended_Date'])

In [30]:
injurydf

,Injury_ID,Athlete_ID,Medical_Staff_ID,Recovery_Started_Date,Event_Injury,Body_Part,Abbreviated_Injury_Scale,Cause_Of_Injury,Recovery_Ended_Date
0,00000,00956,00056,2021-06-19,While Sleeping,Nose,5,Body System Failure,2022-04-07
1,00001,00066,00063,2021-04-16,Daily Life Accident,Mouth,6,Body System Failure,2022-07-08
2,00002,00005,00064,2021-10-24,During Training,Back,3,Body System Failure,2022-04-30
3,00003,00790,00028,2021-06-23,After Training,Teeth,5,Body System Failure,2022-03-10
4,00004,00327,00018,2021-04-09,After Training,Right Eye,3,Tackle,2021-12-05
...,...,...,...,...,...,...,...,...,...
95,00095,00535,00022,2021-05-13,During the match,Teeth,2,Effect after the training or match,2021-12-27
96,00096,00681,00044,2021-10-17,After Training,Left Leg,2,Tackle,2022-05-19
97,00097,00456,00054,2021-09-10,While Sleeping,Right Foot,3,Body System Failure,2022-04-04
98,00098,00859,00016,2021-02-15,After the match,Left Arm,2,Tackle,2022-12-05
99,00099,00646,00015,2021-03-18,While Sleeping,Immune System,3,Tackle,2022-11-26

In [36]:
illnesslist = []
num = 100
start_date = datetime.date(2021, 2, 14)
end_date = datetime.date(2021, 12, 1)

psyco_start = datetime.date(2021, 12, 2)
psyco_end = datetime.date(2022, 12, 14)

Diagonis = ["Malaria","Dengue","Japanese Encephalitis","Leptospirosis","Soil-transmitted worm diseases","Sexually Transmitted Diseases","Tuberculosis","Seasonal Flu","Food Poisoning",
            "Water Borne Diseases","Traffic Accidents","Rabies","Snakebites"]
Symptom = ["Fever","Chills","Congestion","Fatigue","headache","Muscle aches","Bloody diarrhea","Vomiting","Dehydration","Shock"]

for x in range(0,num):
    time_between_dates = end_date - start_date
    days_between_dates = time_between_dates.days
    random_number_of_days = random.randrange(days_between_dates)
    random_date = start_date + datetime.timedelta(days=random_number_of_days)

    tb = psyco_end - psyco_start
    nextstep = tb.days
    nextstepp = random.randrange(nextstep)
    randomstep = psyco_start + datetime.timedelta(days=nextstepp)
    illnesslist.append([str(x).zfill(5),str(random.randint(0,999)).zfill(5),str(random.randint(0,69)).zfill(5),str(random_date),str(random.choice(Diagonis)),str(random.choice(Symptom)),str(randomstep)])
    # print("("
    #  + "'" + str(x).zfill(5) +  "'" +"," + "'" + str(random.randint(0,999)).zfill(5) +"'" + "," + "'" + str(random.randint(0,69)).zfill(5)   + "'"+  "," + 
    #  "'" +str(random_date)+ "'" +"," + "'" + str(random.choice(Diagonis)) + "'" + "," +"'" + str(random.choice(Symptom))+ "'" + ","+ "'" +str(randomstep)+ "'"+
    # ")" + ",")

In [37]:
illnessdf = pd.DataFrame(illnesslist, columns=['Illness_Case_ID','Athlete_ID','Medical_Staff_ID','Recovery_Started_Date','Diagnoses','Symptom','Recovery_Ended_Date'])

In [38]:
illnessdf

,Illness_Case_ID,Athlete_ID,Medical_Staff_ID,Recovery_Started_Date,Diagnoses,Symptom,Recovery_Ended_Date
0,00000,00278,00024,2021-09-03,Soil-transmitted worm diseases,Muscle aches,2022-07-23
1,00001,00883,00058,2021-10-18,Malaria,Vomiting,2022-08-21
2,00002,00532,00035,2021-10-03,Rabies,Fever,2022-03-31
3,00003,00023,00045,2021-08-02,Water Borne Diseases,Fever,2022-07-10
4,00004,00982,00065,2021-11-11,Tuberculosis,Bloody diarrhea,2022-01-18
...,...,...,...,...,...,...,...
95,00095,00699,00027,2021-06-30,Japanese Encephalitis,Fatigue,2022-10-23
96,00096,00385,00010,2021-04-28,Seasonal Flu,Congestion,2022-01-17
97,00097,00400,00005,2021-06-01,Malaria,headache,2022-07-11
98,00098,00707,00028,2021-07-19,Water Borne Diseases,Dehydration,2022-03-21
99,00099,00908,00010,2021-06-06,Soil-transmitted worm diseases,headache,2022-02-01

In [40]:
illnessdf.to_csv('Illness.csv', index=False)
injurydf.to_csv('Injury.csv',index = False)
psycodf.to_csv('Psycological_Case.csv',index = False)
dfmedical.to_csv('Medical_Staff.csv',index =False)
teamdf.to_csv('Sport_Team.csv',index =False)
atdf.to_csv('Athlete.csv',index =False)